// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace gbrainy.Clients.WebForms {
	
	
	public partial class AllGames {
		
		protected System.Web.UI.WebControls.Content main_content;
		
		protected System.Web.UI.WebControls.Repeater games_repeater;
		
		protected System.Web.UI.WebControls.Repeater nexts_repeater;
	}
}
