// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace gbrainy.Clients.WebForms {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Content main_content;
		
		protected System.Web.UI.WebControls.Button start_button;
		
		protected System.Web.UI.WebControls.DropDownList languages_drop;
	}
}
