// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WebForms {


	public partial class Finish {

		protected System.Web.UI.WebControls.Content main_placeholderContent;

		protected System.Web.UI.WebControls.Image image;

		public new WebForms.MasterPage Master {
			get {
				return ((WebForms.MasterPage)(base.Master));
			}
		}
	}
}
