// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace gbrainy.Clients.WebForms {
	
	
	public partial class Game {
		
		protected System.Web.UI.WebControls.Content main_content;
		
		protected System.Web.UI.WebControls.Label allgames_label;
		
		protected System.Web.UI.WebControls.Label endgames_label;
		
		protected System.Web.UI.WebControls.Label question;
		
		protected System.Web.UI.WebControls.Image image;
		
		protected System.Web.UI.WebControls.TextBox answer_textbox;
		
		protected System.Web.UI.WebControls.Button answer_button;
		
		protected System.Web.UI.WebControls.Label result_label;
		
		protected System.Web.UI.WebControls.Label rationale_label;
		
		protected System.Web.UI.WebControls.LinkButton nextgame_link;
		
		protected System.Web.UI.WebControls.Label status;
	}
}
