// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace gbrainy.Clients.WebForms {
	
	
	public partial class Help {
		
		protected System.Web.UI.WebControls.Content main_placeholderContent;
		
		public new gbrainy.Clients.WebForms.MasterPage Master {
			get {
				return ((gbrainy.Clients.WebForms.MasterPage)(base.Master));
			}
		}
	}
}
