// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace gbrainy.Clients.WebForms {
	
	
	public partial class Status {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label updated_label;
		
		protected System.Web.UI.WebControls.Table sessions_table;
		
		protected System.Web.UI.WebControls.Table application_table;
		
		protected System.Web.UI.WebControls.Label total_label;
		
		protected System.Web.UI.WebControls.Label games_label;
		
		protected System.Web.UI.WebControls.Table assemblies_table;
		
		protected System.Web.UI.WebControls.Table counters_table;
	}
}
