.TH GBRAINY 6 "September 12, 2007"

.SH NAME
gbrainy \- A brain teaser game and trainer to have fun and to keep your brain trained

.SH SYNOPSIS
.B gbrainy

.SH "DESCRIPTION"
This manual page documents briefly the application
.BR gbrainy
.PP
.B gbrainy
features different game types like logic puzzles, mental calculation games, memory trainers and verbal analogies designed to test different cognitive skills.
.PP
The player can choose different difficulty levels making gbrainy enjoyable for kids, adults or senior citizens. It also features player's game history, player's personal records, tips for the player and fullscreen mode support. gbrainy can also be extended easily with new games developed by third parties.
.PP
More information about
.B gbrainy
is available on its website, http://live.gnome.org/gbrainy.

.SH BUGS
Please send bug reports to: http://bugzilla.gnome.org/enter_bug.cgi?product=gbrainy

.SH AUTHOR
.B gbrainy
was written by Jordi Mas i Hernandez <jmas@softcatala.org>
.PP
This manual page was written by Siegfried-Angel Gevatter Pujals <siggi.gevatter@gmail.com>,
for the Debian project (but may be used by others).
